### PR TITLE
Opps, forgot to update assets.

### PR DESCRIPTION
**Pull request by ream88**
Sorry about that! (Should not hack on saturday morning)

### CODE REVIEW

**Comment by RyanScottLewis** [comment]
It's all good, github makes simple merges very easy =)

**Comment by ream88** [comment]
Cool! :)

**Comment by RyanScottLewis** [comment]
Also forgot to update the JqTree::Rails::JQTREE_VERSION in lib/jqtree/rails/version.rb - gotta whip up a rake task that does all this in one command.

**Comment by ream88** [comment]
Yes!! Rake task would be super cool! Just say if you need help with that.

**Comment by RyanScottLewis** [comment]
Hey, if you're up to it that'd be great. I could definitely use this process in a few other Rails asset gems.

**Comment by ream88** [comment]
Ok, will work on it asap!

**Comment by RyanScottLewis** [comment]
Thanks! If you want, I could pass add you as a maintainer on the gem & repo so you don't have to wait for me to merge/deploy the updates.

**Comment by ream88** [comment]
Ok with that! :) Thanks man!

On 22.09.2012, at 09:37, Ryan Lewis notifications@github.com wrote:

Thanks! If you want, I could pass add you as a maintainer on the gem & repo
so you don't have to wait for me to merge/deploy the updates.

—
Reply to this email directly or view it on
GitHubhttps://github.com/c00lryguy/jqtree-rails/pull/4#issuecomment-8786381.

**Pull request merged**
