### PR TITLE
Replace version with gem release

### PR DESCRIPTION
**Pull request by ream88**
[gem-release](https://github.com/svenfuchs/gem-release) seems to be more robust and can do the same, plus less dependencies :)

### CODE REVIEW

**Comment by RyanScottLewis** [comment]
Version has no dependencies. Neither does gem release =x Either way works for me, though. You've done alot more maintenance on this project than I have so do whatever works for ya.

**Comment by ream88** [comment]
Yeah, but version was a runtime dependency and I had to do this ugly hack, see #5. I sleep better now :P

**Comment by ream88** [comment]
The hack is actually: a16a7ad1caa367306eebea1d22130cc8b87c805e

**Comment by RyanScottLewis** [comment]
Oh! I use version all the time and I actually fixed this very easily. I made a `gemspec` rake task that doesn't depend on any "gem" rake tasks. It simply builds the gemspec (instead of letting version`do that) by calling`spec.to_ruby`and saves it as`blahblah.gemspec`. Once you do that, you just`bundle install`. That way, when you bump versions, it doesn't complain about missing the`version` dependency.

The only reason I use it as a runtime dependency is that it has some nice logic for finding the `VERSION` file and setting the `VERSION` constant on the libraries main module to the value in the file. But, I think `gem-release` does this as well? I havn't played around much with it. _shrug_

**Pull request merged**
